version: '3.8'

services:
  weatherapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "10900:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro